server:
  port: 8080

logging:
  config: classpath:log4j2.xml

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
      
#minio配置
minio:
  url:   #对象存储服务的URL
  accessKey:  #Access key账户
  secretKey:   #Secret key密码
